language: python
python: '3.8'

branches:
   only:
      - CI

before_script:
   - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="purbeurre.travis_settings"

services:
   - postgresql

script:
   - python3 manage.py test