language: python
python: '3.8'

branches:
   only:
      - CI
before install:
   - wget https://chromedriver.storage.googleapis.com/84.0.4147.30/chromedriver_linux64.zip
   - mkdir chromedriver
   - unzip chromedriver_linux64.zip -d chromedriver
   - export PATH=$PATH:$PWD/chromedriver


before_script:
   - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="purbeurre.travis_settings"

services:
   - postgresql

script:
   - python3 manage.py test